language: node_js
node_js:
  - "6"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
before_script:
  - npm install https://github.com/Apollon77/ioBroker.js-controller/tarball/master --production
env:
  - CXX=g++-4.8
addons:
    apt:
      sources:
          - ubuntu-toolchain-r-test
      packages:
          - g++-4.8
