os:
  - linux
  - osx
  - windows
services:
  - redis-server
language: node_js
node_js:
  - '6'
  - '8'
  - '10'
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install redis; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist; sleep 10; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install redis-64; powershell "$MyProcess = Start-Process redis-server.exe -PassThru"; sleep 10; fi'
  - sleep 15
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo chmod ogu+x test/redis-socket/setup-socket.sh; fi'
script:
  - 'npm test && if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test/redis-socket/setup-socket.sh; fi'
after_success:
  - npm install -g npm@latest
  - npm install --package-lock-only --production
  - npm audit
  - npm ls
after_script:
  - 'if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install redis-64; powershell "Stop-Process -Id $MyProcess.Id"; fi'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
